- name: Install zsh
  apt: pkg=zsh state=installed update_cache=true
  become: yes

- name: Install oh-my-zsh
  action: shell sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
