- name: Update bashrc for JAVA_HOME
  lineinfile:
    dest=/home/{{ whoami.stdout }}/.bashrc
    line="JAVA_HOME=/usr/lib/jvm/default-java"
    state=present
    insertafter=EOF
    create=True
  become: yes

- name: Creates environment directory
  file: path=/home/{{ whoami.stdout }}/Work/environment state=directory

- name: MAVEN | Download and Unarchive Maven 3
  unarchive: src="http://ftp.unicamp.br/pub/apache/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz" dest="/home/{{ whoami.stdout }}/Work/environment" copy=no

- name: Update bashrc for M2_HOME
  lineinfile:
    dest=/home/{{ whoami.stdout }}/.bashrc
    line="M2_HOME=/home/{{ whoami.stdout }}/Work/environment/apache-maven-{{ maven_version }}"
    state=present
    insertafter=EOF
    create=True
  become: yes

- name: Update bashrc for M2
  lineinfile:
    dest=/home/{{ whoami.stdout }}/.bashrc
    line="M2=$M2_HOME/bin"
    state=present
    insertafter=EOF
    create=True
  become: yes

- name: Update bashrc PATH with JAVA_HOME AND M2
  lineinfile:
    dest=/home/{{ whoami.stdout }}/.bashrc
    line="PATH=$PATH:$JAVA_HOME/bin:$M2"
    state=present
    insertafter=EOF
    create=True
  become: yes

- name: Creates IDE directory
  file: path=/home/{{ whoami.stdout }}/Work/IDE state=directory

- name: ECLIPSE | Download and Unarchive Eclipse
  unarchive: src=http://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/mars/2/eclipse-jee-mars-2-linux-gtk-x86_64.tar.gz dest="/home/{{ whoami.stdout }}/Work/IDE" copy=no

- name: Creates Servers directory
  file: path=/home/{{ whoami.stdout }}/Work/servers state=directory

- name: TOMCAT | Download and Unarchive Tomcat
  unarchive: src=http://ftp.unicamp.br/pub/apache/tomcat/tomcat-8/v8.0.33/bin/apache-tomcat-8.0.33.tar.gz dest="/home/{{ whoami.stdout }}/Work/servers" copy=no
