- name: VIRTUALBOX | Download Virtualbox
  get_url: url="http://download.virtualbox.org/virtualbox/5.0.16/virtualbox-5.0_5.0.16-105871~Ubuntu~{{ ubuntu_version }}_amd64.deb" dest=/tmp

- name: VIRTUALBOX | Install Virtualbox
  apt: deb="/tmp/virtualbox-5.0_5.0.16-105871~Ubuntu~{{ ubuntu_version }}_amd64.deb"
  become: yes

- name: VAGRANT | Download Vagrant
  get_url: url="https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb" dest=/tmp

- name: VAGRANT | Install Vagrant
  apt: deb="/tmp/vagrant_{{ vagrant_version }}_x86_64.deb"
  become: yes
